version: "3"

services:
  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 --timeout=20s node index.js
    networks:
      - app-network
    volumes:
      - ./node:/home/node/app
      - node_modules:/home/node/app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - app-network
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: